# .mdformat.toml
#
# This file shows the default values and is equivalent to having
# no configuration file at all. Change the values for non-default
# behavior.
#
wrap = "keep"      # options: {"keep", "no", INTEGER}
number = true      # options: {false, true}
end_of_line = "lf" # options: {"lf", "crlf", "keep"}
validate = true    # options: {false, true}
