name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Rust toolchain + target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi

      - name: Install flip-link
        run: cargo install flip-link

      - name: Build
        working-directory: firmware
        run: cargo lead_barry_build --verbose
